"""Initial migration.

Revision ID: cbeb6955d7ca
Revises: 
Create Date: 2024-02-25 23:09:48.482311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbeb6955d7ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=False, server_default="0.0"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_assets', schema=None) as batch_op:
        batch_op.drop_column('weight')

    # ### end Alembic commands ###
